### ISSUE TITLE
Request: update readme to include build instructions for TestDragon/TestLookingGlassPass

### ISSUE THREAD

**Issue by rmlearney** [Kitware/LookingGlassVTKModule#55]
Managed to get everything to compile on my Mac, now trying to run tests. Would really help to have a little something added to the `readme` :)

**Comment by cjh1** [comment]
We would be happy to accept a PR if you have updates to the `readme` that you think would help others.

**Comment by psavery** [comment]
If you built VTK with Python support, it may be easier to test via `source ./unix_path.sh` and running the [Python examples](https://github.com/Kitware/LookingGlassVTKModule/tree/master/Examples/Python).

For the C++ tests, I think you need to build VTK with `-DVTK_BUILD_TESTING=ON`, and then I think within the build directory you can run a test like this:

```bash
./bin/vtkLookingGlassCxxTests TestDragon -D ./ExternalData/Testing/ -I
```

If that's true, feel free to put up a PR for the README.

**Comment by rmlearney** [comment]
Your advice for the C++ tests worked - thank you :)

Any chance you could submit an addition to the readme?
