### ISSUE TITLE
Set custom value if no LookingGlass is attached

### ISSUE THREAD

**Issue by Timozen** [Kitware/LookingGlassVTKModule#65]
Currently, the `LookingGlassInferace` and, therefore, the `LookingGlassRenderWindow` defaults to `large` if no device is connected. However, I would like to precompute the same scene with several quilt combinations (e.g., 8x6 or 5x9). 

I did not find any documentation to set this value and was wondering if:
a) it is possible to set that, or
b) how much work would it be to make this configurable if not implemented yet

Sincerely,
Tim

**Comment by psavery** [comment]
Hi @Timozen! Yes this is supported. See [here](https://github.com/Kitware/LookingGlassVTKModule/blob/6ea6bfb8e7ab27257dbd54358df2815028063921/Examples/Python/change_devices.py#L37-L39) for an example in Python. Those Python calls of `GetDeviceTypes()` and `SetDeviceType()` have corresponding functions in C++ on the render window.

**Comment by Timozen** [comment]
Oh wow! Thank you very much 👍🏻
I think I just should get some new glasses ^^

This resolves my issue completely!
